name: Unzip and Deploy
on: [push]
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: unzip demo_zedtech.zip -d .
      - run: git add .
      - run: git commit -m "Unzipped files"
      - run: git push
